### ISSUE TITLE
add option 5) Ver inventario in main menu

### ISSUE THREAD

**Issue by Japoivvb** [Dayannadw/Shop_M03_UF5#1]
1. add new option in main menu, click on it or typing 5 a new window must appear with data loaded in inventory as show in below picture

2. set issue label as enhancement to be tracked

3. commit message with #numberIssue verb + details

4. include screenshot in issue once the fix is working and code has been pushed to main branch

5. wait for QA validation

![image](https://github.com/Dayannadw/Shop_M03_UF5/assets/36648472/58ce2382-92b2-4228-bedd-1d24c96670e3)

**Comment by Dayannadw** [comment]
<img width="680" alt="Captura de pantalla 2024-06-03 a las 22 42 08" src="https://github.com/Dayannadw/Shop_M03_UF5/assets/159908214/c9362b74-f61e-44a0-8822-d61bfd6271b1">

**Comment by Dayannadw** [comment]
<img width="443" alt="Captura de pantalla 2024-06-03 a las 22 58 29" src="https://github.com/Dayannadw/Shop_M03_UF5/assets/159908214/db772881-1006-491a-98c6-68d715376b7f">

**Comment by Japoivvb** [comment]
1. ko, the code is incompleted, InventoryView receives the shop object but it is not read to fill the table, check if some code was not commited yet.
2. ok
3. ko, commit message does not have link with issue
4. ok
5. ok
